AWSTemplateFormatVersion: '2010-09-09'
Description: ssmtest microservice.

Parameters:
  ServiceName:
    Type: String
  StageName:
    Type: String
  CodeBucketName:
    Type: String
  CodeKey:
    Type: String
  SwaggerKey:
    Type: String
  NotificationEmail:
    Type: String
  EnvironmentType:
    Type: String
  ClientId:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: '/1ticket/marketplaces/seatgeek/client_id'
    NoEcho: true
  GsProdToken:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: '/1ticket/marketplaces/seatgeek/gs_prod_token'
    NoEcho: true

Conditions:
  UseProdCondition:
    !Equals [!Ref EnvironmentType, prod]

Resources:
  ##########################################################################################
  # Shared Resources / Roles
  ##########################################################################################
  SsmtestBaseRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "AllowLambdaServiceToAssumeRole"
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"

  ##########################################################################################
  # API Gateway configuration
  ##########################################################################################
  Api:
    Type: AWS::ApiGateway::RestApi
    Properties:
      BodyS3Location:
        Bucket: !Ref CodeBucketName
        Key: !Ref SwaggerKey

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref Api

  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Action: "sts:AssumeRole"
          Principal:
            Service:
              - apigateway.amazonaws.com

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref Api
      DeploymentId: !Ref ApiDeployment
      StageName: prod
      Variables:
        ApiRoleName: !Ref ApiRole
        ExampleGetFunctionName: !Ref ExampleGetFunction
        ExamplePostFunctionName: !Ref ExamplePostFunction

  ApiExampleGetFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ExampleGetFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - ":"
          - !Ref Api
          - "/*/*"

  ApiExamplePostFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ExamplePostFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - ":"
          - !Ref Api
          - "/*/*"


  ##########################################################################################
  # Example Get Function -- Handles the example GET request.
  ##########################################################################################
  ExampleGetFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt SsmtestBaseRole.Arn
      Handler: Ssmtest.handlers.example_get
      Runtime: python3.6
      Code:
        S3Bucket: !Ref CodeBucketName
        S3Key: !Ref CodeKey
      MemorySize: 128
      Timeout: 300


  ##########################################################################################
  # Example Post Function -- Handles the example POST request.
  ##########################################################################################
  ExamplePostFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt SsmtestBaseRole.Arn
      Handler: Ssmtest.handlers.example_post
      Runtime: python3.6
      Code:
        S3Bucket: !Ref CodeBucketName
        S3Key: !Ref CodeKey
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          CLIENT_ID: !Ref ClientId
          GS_PROD_TOKEN: !Ref GsProdToken

