AWSTemplateFormatVersion: '2010-09-09'
Description: projectbase microservice.

Parameters:
  ServiceName:
    Type: String
  StageName:
    Type: String
  CodeBucketName:
    Type: String
  CodeKey:
    Type: String
  SwaggerKey:
    Type: String
  NotificationEmail:
    Type: String
  EnvironmentType:
    Type: String
  CreateLogGroup:
    Description: Whether I should create a resource.
    Type: String
    AllowedValues: [true, false]
  EnvironmentType:
    Description: Environment type.
    Type: String
    AllowedValues: [prod, dev]
    ConstraintDescription: must specify prod or dev.
  LogStreamerArn:
    Description: Lambda Arn for Log Streamer function
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: '/dti1ticket/logging/logstream_arn'

Conditions:
  UseProdCondition:
    !Equals [!Ref EnvironmentType, prod]
  ShouldCreateLogGroup:
    !Equals [true, !Ref CreateLogGroup]

Resources:
  ##########################################################################################
  # Shared Resources / Roles
  ##########################################################################################
  projectbaseBaseRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "AllowLambdaServiceToAssumeRole"
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"

  ##########################################################################################
  # API Gateway configuration
  ##########################################################################################
  Api:
    Type: AWS::ApiGateway::RestApi
    Properties:
      BodyS3Location:
        Bucket: !Ref CodeBucketName
        Key: !Ref SwaggerKey

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref Api

  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Action: "sts:AssumeRole"
          Principal:
            Service:
              - apigateway.amazonaws.com

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref Api
      DeploymentId: !Ref ApiDeployment
      StageName: prod
      Variables:
        ApiRoleName: !Ref ApiRole
        ExampleGetFunctionName: !Ref ExampleGetFunction
        ExamplePostFunctionName: !Ref ExamplePostFunction

  ApiExampleGetFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ExampleGetFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - ":"
          - !Ref Api
          - "/*/*"

  ApiExamplePostFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ExamplePostFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - ":"
          - !Ref Api
          - "/*/*"


  ##########################################################################################
  # Example Get Function -- Handles the example GET request.
  ##########################################################################################
  ExampleGetFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt projectbaseBaseRole.Arn
      Handler: projectbase.handlers.example_get
      Runtime: python3.6
      Code:
        S3Bucket: !Ref CodeBucketName
        S3Key: !Ref CodeKey
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          APP_NAME: 'projectbase'


  ##########################################################################################
  # Example Post Function -- Handles the example POST request.
  ##########################################################################################
  ExamplePostFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt projectbaseBaseRole.Arn
      Handler: projectbase.handlers.example_post
      Runtime: python3.6
      Code:
        S3Bucket: !Ref CodeBucketName
        S3Key: !Ref CodeKey
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          APP_NAME: 'projectbase'


  ##########################################################################################
  # Log Ship -- Handles logging to centralized logging account.
  ##########################################################################################
  GetFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Condition: ShouldCreateLogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref ExampleGetFunction]]
      RetentionInDays: 14

  GetFunctionLogGroupWaitHandle: 
    Condition: ShouldCreateLogGroup
    DependsOn: GetFunctionLogGroup
    Type: "AWS::CloudFormation::WaitConditionHandle"

  WaitHandle: 
    Type: "AWS::CloudFormation::WaitConditionHandle"

  GetFunctionLogGroupWaitCondition:
    Type: "AWS::CloudFormation::WaitCondition"
    Properties: 
      Handle: !If [ShouldCreateLogGroup, !Ref GetFunctionLogGroupWaitHandle, !Ref WaitHandle]
      Timeout: "1"
      Count: 0

  GetFunctionSubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    DependsOn: GetFunctionLogGroupWaitCondition
    Properties:
      DestinationArn: !Sub ${LogStreamerArn}
      FilterPattern: ''
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref ExampleGetFunction]]
